# analytics
googleAnalytics = "UA-129126578-2"

baseURL = "/weblogic-image-tool/"
languageCode = "en-us"
title = "WebLogic Image Tool"

# Change the default theme to be use when building the site with Hugo
theme = "hugo-theme-relearn-8.3.0"

publishDir = "docs"

# For search functionality
[outputs]
  home = [ "HTML", "RSS", "JSON"]

[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  hideAuthorDate = true
  # disable the copy to clipboard links
  disableInlineCopyToClipBoard = true
  themeVariant = "learn"
